### ISSUE TITLE
SSL certificates revoked on v5.*.transport.rest subdomains

### ISSUE THREAD

**Issue by nicorsm** [public-transport/transport.rest#12]
Hi 👋  thanks for your great work!
Just want to let you know that right now all `v5.*.transport.rest` endpoints are returning an `ERR_CERT_REVOKED` error... looks like the SSL certificates have been revoked.
```
NET::ERR_CERT_REVOKED
Subject: v5.bvg.transport.rest
Issuer: R3
Expires on: 22 mar 2022
Current date: 30 gen 2022

Certificate Transparency:
SCT Cloudflare 'Nimbus2022' Log (Embedded in certificate, Verified)
SCT Google 'Argon2022' log (Embedded in certificate, Verified)
```

**Comment by derhuerst** [comment]
Thanks for reporting! I also stumbled upon this today, working on a different project that uses `v5.vbb.transport.rest`.

I assume it's due to [their recent `TLS-ALPN-01` problem](https://community.letsencrypt.org/t/2022-01-25-issue-with-tls-alpn-01-validation-method/170450).

I have fetched new certificates, it should be working again now.

**Comment by derhuerst** [comment]
For the record, these were the revoked certificates:

- `v5.bvg.transport.rest`: [crt.sh `5845154464 `](https://crt.sh/?id=5845154464&opt=ocsp)
- `v5.db.transport.rest`: [crt.sh `5869654000 `](https://crt.sh/?id=5869654000&opt=ocsp)
- `v5.hvv.transport.rest`: [crt.sh `5839333063 `](https://crt.sh/?id=5839333063&opt=ocsp)
- `v5.vbb.transport.rest`: [crt.sh `5869653752 `](https://crt.sh/?id=5869653752&opt=ocsp)

**Comment by nicorsm** [comment]
It's working fine! Thanks @derhuerst !
