### ISSUE TITLE
Nottingham City Transport Bus API

### ISSUE THREAD

**Issue by simonprickett** [public-transport/transport.rest#18]
Hi there, I made an API on Cloudflare for Nottingham City Transport bus departures from a given stop ID.  Instructions and endpoint are here:

https://github.com/simonprickett/nctx-stop-api

Feel free to use this!

**Comment by derhuerst** [comment]
Looks very useful! Is it deployed somewhere?

Then you could either directly [connect](https://developers.cloudflare.com/workers/platform/triggers/custom-domains/) e.g. `v1.nottingham-city.transport.rest`, or let me HTTP-redirect to the API.

**Comment by simonprickett** [comment]
Hello yes it operates here: https://nctx.crudworks.workers.dev/?stopId=3390FO07&maxResults=8

Usage info: https://github.com/simonprickett/nctx-stop-api#usage

**Comment by derhuerst** [comment]
Do you want to use a `transport.rest` subdomain with it, e.g. `v1.nottingham-city.transport.rest`?

**Comment by simonprickett** [comment]
Not sure how that'd fit in with the Cloudflare setup (mostly as I haven't looked into it).  If it's something we can do then I don't see why not.

**Comment by derhuerst** [comment]
There seem to be multiple ways to connect a (sub)domain to Cloudflare: https://developers.cloudflare.com/workers/platform/triggers/custom-domains/

Edit: Turns out that only the ["full setup" (via `NS` records)](https://developers.cloudflare.com/dns/zone-setups/full-setup/setup/) is available with a "Free" account, but AFAIK doesn't work with subdomains. The ["partial (`CNAME`) setup"](https://developers.cloudflare.com/dns/zone-setups/partial-setup/) would work technically, but is only available with "Business" & "Enterprise" accounts.
